name = "OptimPackNextGen"
uuid = "080ffe24-4a27-4ab0-ad71-7b624e73ef8d"
authors = ["Éric Thiébaut <https://github.com/emmt>"]
version = "0.1.0"

[deps]
ArrayTools = "1dc0ca97-c5ce-4e77-ac6d-c576ac9d7f27"
LazyAlgebra = "aeaa251e-9d76-11e9-311b-83636bf44738"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OptimPack_jll = "8115cc2e-fb29-5d71-b5cb-a4fb1c5dcd4c"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
julia = "1.3"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "Printf", "Zygote"]
